package Utilities;

import Extent.ExtentManager;

public class TestConfig extends ExtentManager {
	



	
	public static String server="smtp.gmail.com";
	public static String from = "automationapp01@gmail.com";
	public static String password = "Test123$";
	public static String[] to ={"sriram@saasville.com","dkp@unlimitedusers.com"};
	public static String subject = "AppLoading Report";
	
	public static String messageBody ="Report Generated By DineshKumar";
	public static String attachmentPath="C:\\Users\\Dinesh\\eclipse-workspace\\com.apptivo\\reports";
	public static String  attachmentName= "Extent_Tue_May_10_17_39_18_IST_2022.html" ;
	
}
	
	
	
	
